### PR TITLE
Fix: Date Menu when Dash2Panel is used 

### LINKED ISSUE #134: COSMIC breaks Clock/Date Menu when using an alternative to COSMIC Dock
When using an alternative to the COSMIC Dock like [Dash2Panel](https://github.com/home-sweet-gnome/dash-to-panel), COSMIC overwrites the clocks position and thereby breaks the Panel. 
The clock button returns after re/enabling the Dash2Panel extension again or disabling COSMIC. 

Of course it can not be expected, that the compatibility to all gnome extensions is guaranteed, but maybe to some of the bigger once that can enhance the user experience :)

**Screenshots:**
Problem caused by COSMIC:
Screenshot from 2021-07-05 21-48-15
Expected behaviour and after re/enabling Dash2Panel: 
Screenshot from 2021-07-05 21-48-40

### PR DESCRIPTION
**Pull request by tngebauer**
Fixes #134
This is a very simple fix (I'm not very fluent in Javascript) to the missing clock button when Dash2Panel is used.

### CODE REVIEW

File: extension.js [hunk 1]
```diff
@@ -39,6 +39,14 @@ const CLOCK_RIGHT = 2;
 
 let indicatorPad = null;
 function clock_alignment(alignment) {
+    
+    // Clock Alignement breaks Date Menu, when other extensions like Dash2Panel are used
+    let dash2Panel = Main.extensionManager.lookup("dash-to-panel@jderose9.github.com");
+    if(dash2Panel && dash2Panel.stateObj){
```
Comment (ids1024) [inline extension.js]: I believe it's most correct to test `dash2Panel.state == ExtensionUtils.ExtensionState.ENABLED` rather than `dash2Panel.stateObj`, though the effect is probably the same. (Also there probably shouldn't be an empty line before this code, and only one empty line after it).

**Review by ids1024 — COMMENTED** [review]
This generally seems reasonable.

This would make the "Clock Alignment" setting no longer function (when dash2panel is installed).

I'm not sure how correct the behavior is if the Cosmic extension is loaded first, though I guess this doesn't change that. Cosmic would run `clock_alignment`, potentially changing the parent of the clock widget. And nothing would reverse that change when the next extension loads. But again, not really changed here, and the clock's parent should match Gnome Shell's default unless Cosmic's Clock Alignment setting is changed.

File: extension.js (hunk 1 above)
Comment (tngebauer) [reply extension.js]: Yes, the check for the extension is based on the `with_pop_shell` function from [Overview.js](https://github.com/pop-os/cosmic/blob/master_hirsute/overview.js). Checking for the stateObj seemed to do the trick, to make sure that the extension not only exists but is also enabled. 
Removed empty lines and added a proper check in 6144264

**Review by ids1024 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Brings the clock back when using Dash to Panel, setting still works when Dash to Panel is not installed or enabled.
